USE [master]
GO
CREATE DATABASE [EMAILSYSTEM]
 ON PRIMARY 
( NAME = N'EMAILSYSTEM', FILENAME = N'/var/opt/mssql/data/EMAILSYSTEM.mdf', SIZE = 73728KB, MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EMAILSYSTEM_log', FILENAME = N'/var/opt/mssql/data/EMAILSYSTEM_log.ldf', SIZE = 8192KB, MAXSIZE = 2048GB, FILEGROWTH = 65536KB )
GO
ALTER DATABASE [EMAILSYSTEM] SET COMPATIBILITY_LEVEL = 160
GO
ALTER DATABASE [EMAILSYSTEM] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [EMAILSYSTEM] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [EMAILSYSTEM] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [EMAILSYSTEM] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [EMAILSYSTEM] SET ARITHABORT OFF 
GO
ALTER DATABASE [EMAILSYSTEM] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [EMAILSYSTEM] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [EMAILSYSTEM] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [EMAILSYSTEM] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [EMAILSYSTEM] SET CURSOR_DEFAULT GLOBAL 
GO
ALTER DATABASE [EMAILSYSTEM] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [EMAILSYSTEM] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [EMAILSYSTEM] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [EMAILSYSTEM] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [EMAILSYSTEM] SET ENABLE_BROKER 
GO
ALTER DATABASE [EMAILSYSTEM] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [EMAILSYSTEM] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [EMAILSYSTEM] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [EMAILSYSTEM] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [EMAILSYSTEM] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [EMAILSYSTEM] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [EMAILSYSTEM] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [EMAILSYSTEM] SET RECOVERY FULL 
GO
ALTER DATABASE [EMAILSYSTEM] SET MULTI_USER 
GO
ALTER DATABASE [EMAILSYSTEM] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [EMAILSYSTEM] SET DB_CHAINING OFF 
GO
ALTER DATABASE [EMAILSYSTEM] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [EMAILSYSTEM] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [EMAILSYSTEM] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [EMAILSYSTEM] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'EMAILSYSTEM', N'ON'
GO
ALTER DATABASE [EMAILSYSTEM] SET QUERY_STORE = ON
GO
ALTER DATABASE [EMAILSYSTEM] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [EMAILSYSTEM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Contacts](
    [ContactId] [int] IDENTITY(1,1) NOT NULL,
    [Contact_Mail] [nvarchar](100) NOT NULL,
    [ContactOwner] [nvarchar](100) NOT NULL,
    [ContactName] [nvarchar](200) NOT NULL,
PRIMARY KEY CLUSTERED 
(
    [ContactId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[EmailsReceived](
    [EmailReceivedId] [int] IDENTITY(1,1) NOT NULL,
    [Sender] [nvarchar](100) NOT NULL,
    [Receiver] [nvarchar](100) NOT NULL,
    [SentDate] [datetime] NOT NULL,
    [IsRead] [bit] NOT NULL,
    [Folder] [nvarchar](100) NOT NULL,
    [SubjectMail] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
    [EmailReceivedId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
CREATE TABLE [dbo].[EmailsSent](
    [EmailSentId] [int] IDENTITY(1,1) NOT NULL,
    [Sender] [nvarchar](100) NOT NULL,
    [Receiver] [nvarchar](100) NOT NULL,
    [SentDate] [datetime] NOT NULL,
    [IsRead] [bit] NOT NULL,
    [Folder] [nvarchar](100) NOT NULL,
    [SubjectMail] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
    [EmailSentId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
CREATE TABLE [dbo].[Folders](
    [FolderId] [int] IDENTITY(1,1) NOT NULL,
    [FolderName] [nvarchar](100) NOT NULL,
    [OwnerFolder] [nvarchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
    [FolderId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[Logs](
    [LogId] [int] IDENTITY(1,1) NOT NULL,
    [ActionName] [nvarchar](100) NOT NULL,
    [UserEmail] [nvarchar](100) NOT NULL,
    [TimestampLog] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
    [LogId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[MobileAppCredentials](
    [Id] [int] IDENTITY(1,1) NOT NULL,
    [UserEmail] [nvarchar](100) NOT NULL,
    [EmailAccount] [nvarchar](100) NOT NULL,
    [PublicKeyMobile] [nvarchar](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
    [Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
CREATE TABLE [dbo].[Private_Key_Ring](
    [Id] [int] IDENTITY(1,1) NOT NULL,
    [Timestamp] [datetime] NOT NULL,
    [KeyId] [nvarchar](max) NOT NULL,
    [Public_Key] [nvarchar](max) NOT NULL,
    [Private_Key] [nvarchar](max) NOT NULL,
    [UserEmail] [nvarchar](100) NOT NULL,
    [ExpirationDate] [date] NOT NULL,
PRIMARY KEY CLUSTERED 
(
    [Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
CREATE TABLE [dbo].[Public_Key_Ring](
    [Id] [int] IDENTITY(1,1) NOT NULL,
    [Timestamp] [datetime] NOT NULL,
    [KeyId] [nvarchar](max) NOT NULL,
    [Public_Key] [nvarchar](max) NOT NULL,
    [UserEmail] [nvarchar](100) NOT NULL,
    [ExpirationDate] [date] NOT NULL,
PRIMARY KEY CLUSTERED 
(
    [Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
CREATE TABLE [dbo].[Recovery_Credentials](
    [Id] [int] IDENTITY(1,1) NOT NULL,
    [UserEmail] [nvarchar](100) NOT NULL,
    [RecoveryEmail] [nvarchar](100) NOT NULL,
    [Verified] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
    [Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[Recovery_Key_Ring](
    [Id] [int] IDENTITY(1,1) NOT NULL,
    [SessionKey] [nvarchar](max) NOT NULL,
    [UserEmail] [nvarchar](100) NOT NULL,
    [Used] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
    [Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
CREATE TABLE [dbo].[TwoFactorInfo](
    [Id] [int] IDENTITY(1,1) NOT NULL,
    [UserEmail] [nvarchar](100) NOT NULL,
    [KeysId] [nvarchar](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
    [Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
CREATE TABLE [dbo].[Users](
    [UserId] [int] IDENTITY(1,1) NOT NULL,
    [Email] [nvarchar](100) NOT NULL,
    [Password_User] [nvarchar](255) NOT NULL,
    [Full_Name] [nvarchar](100) NOT NULL,
    [Birthday] [date] NULL,
    [Gender] [nvarchar](10) NULL,
    [Phone] [nvarchar](50) NULL,
    [Flag_Reset] [bit] NOT NULL,
    [TwoFactor] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
    [UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
    [Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EmailsReceived] ADD DEFAULT (getdate()) FOR [SentDate]
GO
ALTER TABLE [dbo].[EmailsReceived] ADD DEFAULT ((0)) FOR [IsRead]
GO
ALTER TABLE [dbo].[EmailsReceived] ADD DEFAULT ('Inbox') FOR [Folder]
GO
ALTER TABLE [dbo].[EmailsSent] ADD DEFAULT (getdate()) FOR [SentDate]
GO
ALTER TABLE [dbo].[EmailsSent] ADD DEFAULT ((1)) FOR [IsRead]
GO
ALTER TABLE [dbo].[EmailsSent] ADD DEFAULT ('Sent') FOR [Folder]
GO
ALTER TABLE [dbo].[Logs] ADD DEFAULT (getdate()) FOR [TimestampLog]
GO
ALTER TABLE [dbo].[Private_Key_Ring] ADD DEFAULT (getdate()) FOR [Timestamp]
GO
ALTER TABLE [dbo].[Private_Key_Ring] ADD DEFAULT (dateadd(day,(30),getdate())) FOR [ExpirationDate]
GO
ALTER TABLE [dbo].[Public_Key_Ring] ADD DEFAULT (getdate()) FOR [Timestamp]
GO
ALTER TABLE [dbo].[Public_Key_Ring] ADD DEFAULT (dateadd(day,(30),getdate())) FOR [ExpirationDate]
GO
ALTER TABLE [dbo].[Recovery_Credentials] ADD DEFAULT ((0)) FOR [Verified]
GO
ALTER TABLE [dbo].[Recovery_Key_Ring] ADD DEFAULT ((0)) FOR [Used]
GO
ALTER TABLE [dbo].[Users] ADD DEFAULT ((0)) FOR [Flag_Reset]
GO
ALTER TABLE [dbo].[Users] ADD DEFAULT ((0)) FOR [TwoFactor]
GO
ALTER TABLE [dbo].[Contacts] WITH CHECK ADD FOREIGN KEY([ContactOwner])
REFERENCES [dbo].[Users] ([Email])
GO
ALTER TABLE [dbo].[EmailsReceived] WITH CHECK ADD FOREIGN KEY([Receiver])
REFERENCES [dbo].[Users] ([Email])
GO
ALTER TABLE [dbo].[EmailsSent] WITH CHECK ADD FOREIGN KEY([Sender])
REFERENCES [dbo].[Users] ([Email])
GO
ALTER TABLE [dbo].[Folders] WITH CHECK ADD FOREIGN KEY([OwnerFolder])
REFERENCES [dbo].[Users] ([Email])
GO
ALTER TABLE [dbo].[Recovery_Credentials] WITH CHECK ADD FOREIGN KEY([UserEmail])
REFERENCES [dbo].[Users] ([Email])
GO
ALTER TABLE [dbo].[Recovery_Key_Ring] WITH CHECK ADD FOREIGN KEY([UserEmail])
REFERENCES [dbo].[Users] ([Email])
GO
ALTER TABLE [dbo].[TwoFactorInfo] WITH CHECK ADD FOREIGN KEY([UserEmail])
REFERENCES [dbo].[Users] ([Email])
GO
USE [master]
GO
ALTER DATABASE [EMAILSYSTEM] SET READ_WRITE 
GO
