FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    gcc \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY imap.py .
COPY smtp.py .
COPY s3_client.py .
COPY start_mail.py .
COPY Certificate/ Certificate/

EXPOSE 587 993

CMD ["python", "start_mail.py"]