USE [master]
GO

IF EXISTS (SELECT name FROM sys.databases WHERE name = N'EMAIL_MOBILE')
BEGIN
    ALTER DATABASE [EMAIL_MOBILE] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
    DROP DATABASE [EMAIL_MOBILE]
END
GO

CREATE DATABASE [EMAIL_MOBILE]
 CONTAINMENT = NONE
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
